#!/bin/bash

function usage {
 
 echo "Runs ex-hist registration scripts"
 echo ""
 echo "$0 <in_mri_nii> <in histology_data_dir> <out_ex-hist_reg_data_dir> <subjid> <structure> <session> <optional: -t TH> "
 echo "   -t <th>		Set threshold for ex-vivo MRI (default 50; use 0 if already masked)"
 echo ""
 echo ""
 exit 0 
}

if [ "$#" -lt 6 ]
then

usage

fi

execpath=`dirname $0`


in_mri=$1
hist_dir=$2
out_dir=$3
subj=$4
struct=$5
session=$6 

shift 6


$execpath/1_registerHistToExMRI $in_mri $hist_dir $out_dir $subj $struct $session $@
$execpath/2_generateFinalXfms  $out_dir $subj $struct $session
$execpath/3_resampleTo100um $out_dir $in_mri $subj $struct $session



