#!/bin/bash


if [ "$#" -lt 4 ]
then
 echo "Usage: $0 <ex_hist_reg_rootdir> <subj> <structure>  <session>"
 echo ""
 echo " e.g.:  $0 ~/EpilepsyDatabase/epilepsyPhase1/Ex-Hist_Reg EPI_P014 Neo" # Post_fix"
 echo ""
 exit
fi

data_dir=$1
subj=$2
struct=$3
session=$4

mri=`ls $data_dir/$subj/*/$struct/3drigid_iter5/reg_ex_mri.nii.gz | head -n 1`
if [ ! -n "$mri" ]
then 
 echo $subj mri does not exist!
 exit 0
fi
#session=${mri##${data_dir}/${subj}/}
#session=${session%%/*}

echo mri: $mri
echo subj: $subj
echo struct: $struct
echo session: $session

echo  runMatlabCmd genFinalTransforms "'$data_dir'" "'$subj'" "'$struct'" "'$session'"
runMatlabCmd genFinalTransforms "'$data_dir'" "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd transformCoordHistToMRI "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd TransformHistFidstoExNew "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd computeTRExHistNew "'$subj'" "'$struct'" "'$session'"



