#!/bin/bash

if [ "$#" -lt 4 ]
then
echo "Usage: $0 <data_dir> <structure - Hp or Neo>  <resolution - 100, 20>  <annotation_name> <subjids>"
exit 0
fi

data_dir=$1
structure=$2
resolution=$3
annot_name=$4




shift 4


for subj in $@
do

 annot_folder=$data_dir/$subj/annotations/$annot_name
 #echo runMatlabCmd loadHistologyAnnotation "'$annot_folder'" "$resolution"
 runMatlabCmd loadHistologyAnnotation "'$annot_folder'" "$resolution"
 


done
