#!/bin/bash



if [ "$#" -lt 5 ]
then
 echo "This script converts feature-map MAT files to nifti, making use of histology orientation cfg files"
 echo "Usage: $0 <data_dir> <structure> <stain>  <featuremapdir - e.g.: 100um_FeatureMaps> <subject ids ...>"
 exit 0
fi

hist_dir=$1
struct=$2
stain=$3
feat_dir=$4
shift 4

ref_stain=LFB

#by default, use these as orientation vars:
orient_vars=""

if [ "${feat_dir: -11}" = "FeatureMaps" ]
then
 orient_vars="{'orientation','weighted_orientation'}"
fi


if [ "${feat_dir: -9}" = "Laplacian" ]
then
  orient_vars="{'laplace_grad'}"
fi

if [ "${feat_dir: -17}" = "StructuralTensors" ]
then
  orient_vars="{'major_angle'}"
fi

if [ "${feat_dir: -8}" = "vonMises" ]
then
  orient_vars="{'mu','mu1','mu2'}"
fi


for subj in $@
do
 work_dir=$hist_dir/$subj/$feat_dir

 coreg_dir=$hist_dir/$subj/coregisterTo${ref_stain}
 
 for tif in `ls  $hist_dir/$subj/tif/${subj}_${struct}_*_${stain}.tif`
 do

  prefix=${tif##*/}
  prefix=${prefix%.tif}
  
  matfile=$work_dir/$prefix.mat
 if [ -e $matfile  ]
 then
  echo runMatlabCmd convertFeatureMapToNifti "'$feat_dir'" "'$tif'"
  runMatlabCmd convertFeatureMapToNifti "'$feat_dir'" "'$tif'"

  if [ -n "$orient_vars" ]
  then
  echo runMatlabCmd convertOrientationFeatureMapToNifti "'$feat_dir'" "$orient_vars" "'$tif'"
  runMatlabCmd convertOrientationFeatureMapToNifti "'$feat_dir'" "$orient_vars" "'$tif'"
  fi
 else
  echo "mat file for feature vec, $matfile, does not exist!"  
  continue
 fi
 

 #apply H&E reg warp
 flirt_xfm=$coreg_dir/flirt_${prefix}-${ref_stain}.xfm
 inhdr=$coreg_dir/${prefix}.grayscale.nii.gz

 if [ ! -e $flirt_xfm -o ! -e $inhdr ]
 then
   echo "coregistration from $prefix to ${ref_stain} not run for $subj yet, run it in coregisterStains module"
   continue
 fi

 first_nii=`ls $work_dir/histspace/*/$prefix.nii.gz | head -n 1` 
 ref_100um=$coreg_dir/${prefix}_reg${ref_stain}.grayscale.nii.gz

 res_mm=`fslval $first_nii pixdim1`
 res_mm=`echo $res_mm | sed 's/0\{1,\}$//'`
 echo res_mm: $res_mm
 if [ "$res_mm" = "0.1" ]
 then
  ref=$ref_100um
 else
  ref=$coreg_dir/${prefix}_reg${ref_stain}.grayscale.${res_mm}mm.nii.gz
  echo mri_convert $ref_100um -vs $res_mm $res_mm 1 $ref
   mri_convert $ref_100um -vs $res_mm $res_mm 1 $ref
 fi
 

 for nii in `ls $work_dir/histspace/*/$prefix.nii.gz`
 do

 reg=${nii%%.nii.gz}_reg${ref_stain}.nii.gz

 imtype=${nii##*histspace/}
 imtype=${imtype:0:6} #get 1st 6 chars
 echo "imtype: $imtype"
 
 if [ "$imtype" = "vector" ]
 then

 #deal with orientation things here  
echo flirt -in $nii -init $flirt_xfm -applyxfm -ref $ref -out $reg -2D -interp nearestneighbour
 flirt -in $nii -init $flirt_xfm -applyxfm -ref $ref -out $reg -2D -interp nearestneighbour

 reoriented=${nii%%.nii.gz}_reg${ref_stain}.reoriented.nii.gz
 runMatlabCmd reorientVecField "'$reg'" "'$flirt_xfm'" "'$reoriented'" 1


else

# echo fslcpgeom $inhdr $nii
# fslcpgeom $inhdr $nii

 echo flirt -in $nii -init $flirt_xfm -applyxfm -ref $ref -out $reg -2D -interp nearestneighbour
 flirt -in $nii -init $flirt_xfm -applyxfm -ref $ref -out $reg -2D -interp nearestneighbour

fi


 done #nii  (once for each feature)


 #convert RGB_nii if exists'
 red=$work_dir/histspace/red
 green=$work_dir/histspace/green
 blue=$work_dir/histspace/blue
 prefix=${tif##*/}
 prefix=${prefix%%.tif}
echo "prefix: $prefix, red $red "
 if [ -e $red -a -e $green -a -e $blue ]
 then
  rgb=$work_dir/histspace/$prefix.nii.gz
  convertNiftiRGBtoRGB24bit $red/$prefix.nii.gz $green/$prefix.nii.gz $blue/$prefix.nii.gz $rgb
 fi

 done #tif

done
