#!/bin/bash


if [ "$#" -lt 6 ]
then
echo "Usage: $0 <in_hist_dir> <out_root_dir> <structure - Hp/Neo/SubcortL/SubcortR ..> <stain>  <resolution - 100, 20> <subjids>"
exit 0
fi

data_dir=$1
out_dir=$2
structure=$3
stain=$4
resolution=$5



shift 5

for subj in $@
do


 echo runMatlabCmd generateGrayscaleRGB_JPX "'$data_dir'" "'$subj'" "'$structure'" "'$stain'" "$resolution" "'$out_dir'" 
 runMatlabCmd generateGrayscaleRGB_JPX "'$data_dir'" "'$subj'" "'$structure'" "'$stain'" "$resolution" "'$out_dir'" 
 


done
