#!/bin/bash

execpath=`dirname $0`
execpath=`realpath $execpath`



source $execpath/000_setup



if [ "$#" -lt 3 ]
then
	echo "Usage: $0 <out_res> <out_pad> <subj...>"
        echo "    out_res: sets size and stride of NxN sliding window to compute and summarize features (units: um)"
        echo "    out_pad: sets padding on sliding window, without changing the stride. (units: um)"	
	echo "" 
	echo " e.g.: ./05_genPatches 100 200 \`cat subjects.txt \`"
	exit 0
fi

out_res=$1
out_pad=$2

struct=Neo
stain=NEUN
shift 2

#02_genFeatureMaps writes all commands to stdout if ECHO_ONLY is set to 1.. using this to create a joblist
joblist=$jobs_dir/genPatches.list.$out_res.$out_pad
if [ -e $joblist ]; then rm -f $joblist; fi
for subj in $@
do

  for tif in `ls  $in_root_dir/$subj/tif/*${structure}*${stain}.{tif,svs}`
  do
   echo runMatlabCmd generatePatches "'$tif'" $out_res $out_pad "'$out_root_dir'" >> $joblist
  done

done

pushd $jobs_dir/../
#can use -t option for test mode
joblistSubmit $joblist -E $execpath/000_setup -j 2core8gb16h  -t
popd

