#!/bin/bash


if [ "$#" -lt 4 ]
then
echo "Usage: $0 <data_dir> <structure - Hp/Neo/SubcortL/SubcortR ..>  <resolution - 100, 20> <subjids>"
exit 0
fi

data_dir=$1
structure=$2
resolution=$3


shift 3

for subj in $@
do


 for tif in `ls  $data_dir/$subj/tif/*${structure}*.tif`
 do

 echo runMatlabCmd generateGrayscaleRGB "'$tif'" "$resolution" 
 runMatlabCmd generateGrayscaleRGB "'$tif'" "$resolution" 
done


done
