#!/bin/bash


if [ "$#" -lt 4 ]
then
echo "Usage: $0 <Histology Name - i.e. Histology or Histology_Neo> <structure - Hp or Neo>  <stain - e.g. NEUN>  <resolution - 100, 20>  <subjids>"
exit 0
fi

hist_name=$1
structure=$2
stain=$3
resolution=$4


padding=0

data_dir=/eq-nas/$USER/EpilepsyHistology/$hist_name




shift 4


for subj in $@
do


 for tif in `ls  $data_dir/$subj/tif/*${structure}*${stain}*.tif`
 do

 echo "runMatlabCmd generateFieldFraction "'$tif'" "$resolution" "$padding""
 runMatlabCmd generateFieldFraction "'$tif'" "$resolution" "$padding"
done


done
