#!/bin/bash


if [ "$#" -lt 6 ]
then
	echo "Usage: $0 <in_root_dir> <out_root_dir> <struct> <stain> <out_res> <out_pad> <subjids ...>"
	echo "    in_root_dir:  root folder, will read from  {subj}/tif/{subj}_{struct}_{slidenum}_{stain}.tif"
	echo "    out_root_dir: output folder, will create {subj}/{out_res}um_{out_pad}umPad_FeatureMaps"
	echo "    struct: to select structures to process e.g. Hp or Neo"
	echo "    stain: to select stains to process e.g. NEUN "
	echo "    out_res: sets size and stride of NxN sliding window to compute and summarize features (units: um)"
	echo "    out_pad: sets padding on sliding window, without changing the stride. (units: um)"
	echo ""
exit 0
fi
in_root_dir=$1
out_root_dir=$2
structure=$3
stain=$4  # for this always has to be NEUN
resolution=$5
padding=$6


shift 6


for subj in $@
do


 for tif in `ls  $in_root_dir/$subj/tif/*${structure}*${stain}*.tif`
 do

 if [ "$ECHO_ONLY" = "1"  ]
 then
 echo "runMatlabCmd generateFeatureMaps '$tif' $resolution $padding '$out_root_dir'"
 else
 runMatlabCmd generateFeatureMaps "'$tif'" "$resolution" "$padding" "'$out_root_dir'"
 fi
done


done
